apiVersion: v1
kind: ConfigMap
metadata:
  name: clean-architecture-config
data:
  application.yml: |
    spring:
      jpa:
        hibernate:
          ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-description: "init"
        baseline-version: 0
    
    management:
      endpoints:
        web:
          exposure:
            include: health, metrics, info
          base-path: /api/v1/actuator
    
    server:
      port: 8082