apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - ingress.yaml
  - configmap.yaml